name: CI

on:
  push:
    branches: [ "dev"]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.15.1"

      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.55.0"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Setup...
        run: scripts/setup.sh

      - name: Build...
        run: scarb --release build &&
             ./scripts/build-solidity.sh

      - name: Run Tests...
        run: scripts/tests.sh && scarb test
